### ISSUE TITLE
Can't join server: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128437_(String. int)" because "nbt" is null

### ISSUE THREAD

**Issue by MarizPOG** [hlysine/create_power_loader#21]
I've discovered that Create, Create: Steam and Rails, Create: New Age, and Create: Power Loader are incompatible with each other once a train station is placed. Doing so results in being immediately disconnected from the server with the following error message: "**Connection Lost: Internal Exception: java.lang.NullPointerException: Cannot invoke 'net.minecraft.nbt.CompoundTag.getString(String, int)' because 'nbt' is null.**"
Ithundxr mentioned that this issue might stem from the mod introducing mixins to the Create mod, causing errors, hence my report here. This problem seems similar to those documented in [Create issue #6032](https://github.com/Creators-of-Create/Create/issues/6032) and [Railway issue #408](https://github.com/Layers-of-Railways/Railway/issues/408). Notably, this issue only exists on servers; the same setup functions correctly in singleplayer.
[Client debug log](https://mclo.gs/I2P5TIP)
[Client latest log](https://mclo.gs/A2Ai778)
[Server debug log](https://mclo.gs/k0LZMSp)
[Server latest log](https://mclo.gs/odV7DjQ)

**Comment by hlysine** [comment]
Power Loader does patch the nbt read/write functions of train stations, but it is only accessing ita own CPLData compound tag and there are null checks in place. I can't find any references of nbt.getString in Power Loader's code and the provided logs show no relevant stack trace.

I may debug this later with a better setup, but I don't have the time to do that right now.

**Comment by MarizPOG** [comment]
I'm not sure how much assistance I can provide, but I've got logs from this video below  Here are the server debug logs since my connection to the server: [Server Debug Log](https://mclo.gs/h0021s9#L15813). 
Additionally, here are client logs. Before I joined the server i tested singleplayer and it worked correctly: [Client Debug Log](https://mclo.gs/TdL8rR9#L18648).

https://github.com/hlysine/create_power_loader/assets/90553633/b47edeca-6c7e-4795-a38b-0ebd5bc5b1df

**Comment by DJAMIRSAM** [comment]
I can Confirm deleting Power Loaders fixed the problem, also it seems to only effect certain players.

**Comment by GGORG0** [comment]
I am also experiencing the same exact issue.
I never got kicked from the server, but the error got thrown in the `Loading terrain...` phase.
Sometimes I would be able to join just fine, but my friends would get kicked immediately, even if we logged out in the same spot.
Sometimes restarting the client or server helped, other times it worsened the situation.
There was absolutely no mention of this error in the server nor the client logs. Only the error screen.

Uninstalling Create Power Loader from the server didn't do anything. I had to uninstall it both on the server AND client to join reliably.

**Comment by aliaddas** [comment]
Same issue over here, this mod is trivial for so many contraptions. Eagerly waiting for a fix

**Comment by DannyLeWasTaken** [comment]
Confirm issue persists here as well.

**Comment by hlysine** [comment]
I've tried running a 1.20.1 server with debugger attached and couldn't reproduce this bug unfortunately. 

My mod list:
```
Forge - 47.2.5
Flywheel - 0.6.10-7
Create - 0.5.1.f-26
Create: Power Loader - 1.4.0-mc1.20.1
Create: Steam n Rails - 1.6.3+forge-mc1.20.1
Botarium 2.3.3
Create: New Age - 1.1.2
```

If any of you manages to reproduce this bug reliably, please send me your mod list with the exact version of each mod along with your Minecraft and Forge version.

**Comment by MarizPOG** [comment]
The problem is with Neoforge. Forge version 47.2.30 (latest) and 47.2.0 (recommended) worked for me without any issues. However if you change Forge to Neoforge e.g. 47.1.105 (latest) than it doesn't work. That's why you couldn't reproduce the bug. Modlist:
botarium-forge-1.20.1-2.3.3
create_power_loader-1.4.0-mc1.20.1
create-1.20.1-0.5.1.f
create-new-age-forge-1.20.1-1.1.2
kotlinforforge-4.10.0-all
Steam_Rails-1.6.3+forge-mc1.20.1

**Comment by MartianSheep** [comment]
I encountered the same problem recently. I did some test and here are the results. The problem is probably a bit more complicated.
All the testing results are under Minecraft 1.20.1, OS: Windows 10. I set up a simple forge server on the same computer that my client side is executing, so I'm simply connecting localhost:25565, which means there should be no internet issues.

If one uses the modlist:
(both server side and client side)
- Forge 47.2.0
- botarium-forge-1.20.1-2.3.3
- create-power_loader-1.4.0-mc1.20.1
- create-1.20.1-0.5.1
- create-new-age-forge-1.20.1-1.1.2
- Steam_Rails-1.6.3-forge-mc1.20.1

This setup works for me smoothly.

However, if the client side attempts to add some client-side only mods, for example here is the modlist of the client side:
(only the client side changes, the server side remains unchanged)
- Forge 47.2.0
**- appleskin-forge-mc1.20.1-2.5.1**
**- BetterF3-7.0.2-Forge-1.20.1**
- botarium-forge-1.20.1-2.3.3
- cloth-config-11.1.118-forge
- create-power_loader-1.4.0-mc1.20.1
- create-1.20.1-0.5.1
- create-new-age-forge-1.20.1-1.1.2
- Steam_Rails-1.6.3-forge-mc1.20.1

Then this error shows up.

Note that in the example below, if the client only adds appleskin, the game works fine. If the client only adds BetterF3 and cloth config, the game works fine too. The problem only occurs when both "client-side mods" are added.

Here is the server log:

> [21:19:35] [User Authenticator #1/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player MartianSheep is [sensored]
> [21:19:37] [Server thread/INFO] [minecraft/PlayerList]: MartianSheep[sensored] logged in with entity id 190 at (-334.52102119568764, 129.78337312169583, 193.4465959106395)
> [21:19:37] [Server thread/INFO] [minecraft/MinecraftServer]: MartianSheep joined the game
> [21:19:38] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: MartianSheep lost connection: Disconnected
> [21:19:38] [Server thread/INFO] [minecraft/MinecraftServer]: MartianSheep left the game

And here is the client record, starting from the first connection:

> [21:19:34] [Render thread/INFO] [minecraft/ConnectScreen]: Connecting to [sensored], 25565
> [21:19:37] [Netty Client IO #0/INFO] [ne.mi.ne.NetworkHooks/]: Connected to a modded server.
> [21:19:37] [Render thread/INFO] [BatchExecutor/]: Started 10 worker threads
> Finalizing energy item registration
> Finalizing fluid item registration
> org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 356: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
> 	at org.objectweb.asm.tree.analysis@9.5/org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:717)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:686)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:640)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:610)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:436)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:335)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:154)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:148)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.versions.MixinVersionImpl_v0_8_4.makeLvtContext(MixinVersionImpl_v0_8_4.java:19)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.utils.CompatibilityHelper.makeLvtContext(CompatibilityHelper.java:25)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.getOrCreateLocalContext(LocalSugarApplicator.java:129)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.validate(LocalSugarApplicator.java:40)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.sugar.impl.SugarInjector.validateApplicators(SugarInjector.java:171)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.sugar.impl.SugarInjector.prepareSugar(SugarInjector.java:153)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.prepare(SugarWrapperImpl.java:67)
> 	at TRANSFORMER/MixinExtras@0.3.5/com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.prepare(WrapperInjectionInfo.java:57)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.trains.track.TrackPlacementOverlay.render(TrackPlacementOverlay.java:27)
> 	at TRANSFORMER/forge@47.2.0/net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126)
> 	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
> 	at TRANSFORMER/forge@47.2.0/net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:945)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
> 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
> Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
> 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.asm.MixinVerifier.isAssignableFrom(MixinVerifier.java:104)
> 	at org.objectweb.asm.tree.analysis@9.5/org.objectweb.asm.tree.analysis.SimpleVerifier.merge(SimpleVerifier.java:249)
> 	at org.objectweb.asm.tree.analysis@9.5/org.objectweb.asm.tree.analysis.SimpleVerifier.merge(SimpleVerifier.java:42)
> 	at org.objectweb.asm.tree.analysis@9.5/org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:704)
> 	at org.objectweb.asm.tree.analysis@9.5/org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:629)
> 	at org.objectweb.asm.tree.analysis@9.5/org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:245)
> 	... 67 more

And there you go, the error screen:
![圖片](https://github.com/hlysine/create_power_loader/assets/30976432/1a041e7b-f53d-4439-93b3-4157aa070a3c)

If one attempts to connect again, the record only shows:

> [21:25:53] [Render thread/INFO] [minecraft/ConnectScreen]: Connecting to [sensored], 25565
> [21:25:56] [Netty Client IO #1/INFO] [ne.mi.ne.NetworkHooks/]: Connected to a modded server.

And the error screen shows again, without any futher information.

By the way, if we remove the power loader mod on both client and server side, the game works. If we remove the new age mod on both client and server side, the game works too.

**Comment by hlysine** [comment]
@MartianSheep Thanks for the detailed report. I've successfully reproduced this in a debugging setup. Working on a fix right now.

**Comment by hlysine** [comment]
Create: Power Loader v1.5.0 should fix this issue. The update is now live on Modrinth/Curseforge.

**Comment by BaeLeaph** [comment]
I just had this issue pop up today and used Power Loader v1.5.0. It worked for a little, but then after I took a break and came back, it didn't. I also added some new horror mods so they could also be the problem? I tried removing the create mods, but I still had the problem. I also added the Power Loader v1.5.0 without the create mods and it still happened. Does anyone have any idea how to help??

**Comment by hlysine** [comment]
@BaeLeaph Are you sure you are using v1.5 on both the server and the client? Does the error disappear when Power Loader is removed?

**Comment by BaeLeaph** [comment]
@hlysine I just removed all the mods and then put them back in, minus the create mods 😭

**Comment by hlysine** [comment]
Please open a new issue if you manage to confirm Power Loader as the mod causing your issue, since this issue can be caused by many other unrelated reasons.

**Comment by Orphero** [comment]
@hlysine How did you fix the glitch? I've been stuck on trying to fix this in my mod because whenever a player joins a server with my mod this glitch happens. This is the only page that I've seen discussing the glitch so you're my only lead.

**Comment by hlysine** [comment]
I'm not sure if your situation is exactly the same, since the error message is very generic and it was a mixin incompatibility that caused the crash in Power Loader. This is the commit that fixed the issue: https://github.com/hlysine/create_power_loader/commit/98bfbff4a41284b0ecba93b4bb4c66339dfdcfac

Try exporting the mixin-processed classes to inspect the final code, or attach a debugger to the server instance and break on this exception.

**Comment by JoyfulKoinu** [comment]
The commit/newest patch doesn't seem to solve this fully, as my modpack currently has the exact same issue MartianSheep did, while I have been unable to get the same level of information they were, I got quite literally the exact same error message he did. I am on the newest version of power loader for 1.20.1, which is 1.5.0, which I believe is the commit that is supposed to have solved this issue. I am hosting the server off my own PC same as Martian. In an attempt to stop this issue, I removed steam and rails, however this issue persists, which leads me to believe its not solely a conflict with that trio of mods, I have reset all associated server files in an attempt to prevent anything tainting the server files, and it has no resolved it. I can provide the mod list if that is helpful, though it should be listed within the log file. Seemingly restarting the entire Minecraft client can temporarily resolve this issue, but every time you leave the server or restart the server, it seems to return. 

[latest.log](https://github.com/user-attachments/files/16743365/latest.log)
This is my latest.log for you to look through in case this will provide any useful information. There is no related file in crash-reports. If there's any way to provide any additional useful information, please let me know and I will do my best to provide it

**Comment by DJAMIRSAM** [comment]
My Players are Also Experiencing this Exact Error, unfortunately we have resorted to removing Power loader

**Comment by iKingMakina** [comment]
Im experiencing the same problem here but the thing is that i dont use power loader, just create mod and some other mods, here is the modlist
Aether
Alexcaves
Alexmobs
Amendments
AppleSkin
Aquaculture
Aquamirae
Architectury
Ars Nouveau
ATi Structures
Attribute Fix
Balm Forge
Better Third Person
Beyond Earth
Bloodmagic
Call of yucatan
Chisels and bits
Citadel
Cloth Config
Comforts
Connector
Coroutil
*Create*
Creeper Overhaul
Critters n Crawlers
Cupboard
Curios Forge
CustomNPCS non oficial
Decorative Blocks
Decorative Storage
Dungeons Plus
Dungeons and Taverns
Ecologics
Exotic Birds
Fabric API
Fast Leaf Decay
Middle Ages
Framework
Geckolib
Gravestone
Jade
Jei
JourneyMap
L_Enders Cataclysm
Lionfish API
Luckperms
Luminous Beast
Mcw bridges
Mcw fences
Mcw Furniture
Mcw Paths
Mcw roofs
Moonlight
Mowzies mobs
Naturalist
Obscure api
Octolib
Oculus
Patchouli
Projectile damage
Refurbished furniture
Relics
Replay mod
Resourceful config
Simple farming
Skins 3D layer
Sleep
Soulslike weaponry
Structure gel
Structure essentials
Supplementaries
Tax Tree giant
Terralith
The bumblezone
The undergarden
Voice chat
Waystones
Worldedit
Xenon
Yungs API
Yungs dessert temples, etc....

The thing here is that me and my friends wanna do a rpg server with those mods but doing the lobby we realised we sometimes cant enter the server because of that error, i sometimes need to try 5 fives times to enter the server, im not sure if its create but in the lobby there are some elevators so im going to try to remove create mod and remove elevators, if problem dissapears, the problem is create mod. By the way the version is Forge 1.20.1

**Comment by iKingMakina** [comment]
Alr the problem is not create mod beacuse i removed it and it still appears, i dont know what else to try, i even installed latest java version and the problem persists, i would like an solution.

**Comment by iKingMakina** [comment]
Ok so my problem seems to be solved by deleting client mods from the server files so only the player has them, mods like: skin layer 3D, Jade. Jei, AppleSkin, and other client mods. Also i tried putting back create mod and it kicks me with that error, then i deleted it back and i dont have that error anymore. Solution: **Delete create (sadly) and delete client mods from server files.**

**Comment by hlysine** [comment]
This error is very generic and can happen to any mod with networking code. I'm guessing many people arrived here by searching for the error text, but this is the issue page for Create: Power Loader and it is unlikely that your error has the same cause as OP.

If you can reproduce the error with a minimal set of mods, including Create: Power Loader, and removing Power Loader fixes your error, please open a new issue so I can further investigate. Otherwise, there's nothing I can do to help with your specific situation.
